- name: "Configure all Compton settings in '{{ compton_config_path }}'"
  ansible.builtin.template:
    dest: "{{ compton_config_path }}"
    src: "compton_conf.j2"
    owner: 'root'
    mode: '644'
    force: true
  become: true
  become_user: root

