- name: "Do configuration tasks for Linux"
  ansible.builtin.include_tasks: do_configure.yml
  vars:
    compton_config_path: "{{ linux_compton_config_path }}"
  when: ansible_system == "Linux"

- name: "Do configuration tasks for FreeBSD"
  ansible.builtin.include_tasks: do_configure.yml
  vars:
    compton_config_path: "{{ freebsd_compton_config_path }}"
  when: ansible_os_family == "FreeBSD"

